table dim_data
	lineageTag: c8db5ff9-1758-41ef-9e69-2c7195ca3b6a

	column dt_matricula
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9a66bdf3-5343-4038-ac54-de466a3f3e8f
		summarizeBy: none
		sourceColumn: dt_matricula

		variation Variation
			isDefault
			relationship: 6f020454-c6ba-4d2c-8175-03f3c1578255
			defaultHierarchy: LocalDateTable_0c3b543b-035d-45a4-afa5-e64a2e3621a8.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column dt_fim
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3a5f0d15-4817-4f70-86f0-47289346e777
		summarizeBy: none
		sourceColumn: dt_fim

		variation Variation
			isDefault
			relationship: 6c419511-154c-4347-b978-1de1b2373591
			defaultHierarchy: LocalDateTable_360bd347-aad2-4dc1-8f00-32e52bc19090.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition dim_data = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\Rebeca\Desktop\amostra_evg.csv"),[Delimiter=",", Columns=25, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"cod_matricula", type text}, {"dt_matricula", type datetime}, {"nacionalidade", type text}, {"cod_turma", Int64.Type}, {"nome_turma", type text}, {"modalidade_turma", type text}, {"cod_curso", Int64.Type}, {"nome_curso", type text}, {"carga_horaria", Int64.Type}, {"dt_fim", type datetime}, {"sit_turma", type text}, {"instituicao", type text}, {"municipio_pessoa", type text}, {"uf_pessoa", type text}, {"conteudista", type text}, {"tematica", type text}, {"codigo_pessoa", type text}, {"sexo", type text}, {"idade", Int64.Type}, {"sit_matricula", type text}, {"poder", type text}, {"esfera", type text}, {"email_pessoa", type text}, {"telefone_pessoa", Int64.Type}, {"email_conteudista", type text}}),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Tipo Alterado",{"cod_matricula", "dt_matricula", "sit_matricula", "dt_fim", "cod_turma", "cod_curso", "codigo_pessoa"}),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Outras Colunas Removidas",{"cod_matricula", "sit_matricula", "dt_matricula", "dt_fim", "cod_turma", "cod_curso", "codigo_pessoa"}),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Colunas Reordenadas", {"cod_curso"}, dim_curso, {"cod_curso"}, "dim_curso", JoinKind.LeftOuter),
				    #"Consultas Mescladas1" = Table.NestedJoin(#"Consultas Mescladas", {"codigo_pessoa"}, dim_pessoa, {"codigo_pessoa"}, "dim_pessoa", JoinKind.LeftOuter),
				    #"Consultas Mescladas2" = Table.NestedJoin(#"Consultas Mescladas1", {"cod_turma"}, dim_turma, {"cod_turma"}, "dim_turma", JoinKind.LeftOuter),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Consultas Mescladas2",{"cod_turma", "cod_curso", "codigo_pessoa"}),
				    #"dim_curso Expandido" = Table.ExpandTableColumn(#"Colunas Removidas", "dim_curso", {"cod_curso"}, {"cod_curso"}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"dim_curso Expandido",{{"cod_curso", "fk_curso"}}),
				    #"dim_pessoa Expandido" = Table.ExpandTableColumn(#"Colunas Renomeadas", "dim_pessoa", {"codigo_pessoa"}, {"codigo_pessoa"}),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"dim_pessoa Expandido",{{"codigo_pessoa", "fk_pessoa"}}),
				    #"dim_turma Expandido" = Table.ExpandTableColumn(#"Colunas Renomeadas1", "dim_turma", {"cod_turma"}, {"cod_turma"}),
				    #"Colunas Renomeadas2" = Table.RenameColumns(#"dim_turma Expandido",{{"cod_turma", "fk_turma"}}),
				    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Colunas Renomeadas2",{"dt_matricula", "dt_fim"}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Outras Colunas Removidas1",{{"dt_matricula", type date}, {"dt_fim", type date}}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Tipo Alterado1", {"dt_matricula"})
				in
				    #"Duplicatas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

